In [8]:
#first
Print_values
a=np.random.randint(0,10,1)
b=np.random.randint(0,10,1)
c=np.random.randint(0,10,1)
print(a,b,c)
np.where(a>b)
if np.where(a>b)is true:
    if np.where(b>c)is true:
        print(a,b,c)
    else if np.where(a>c)is true
        print(a,c,b)
    else
        print(c,a,b)
else np.where(b>c)is false:
        print(c,b,a)
    

SyntaxError: invalid syntax (3918638493.py, line 10)

In [20]:
#second
import numpy as np
import math
N=np.random.randint(0,10,10)

for x in N:
    f=math.ceil(x/3)
    F(x) = F(f) + 2x
    print(N,F)

SyntaxError: cannot assign to function call (3426132548.py, line 8)

In [21]:
#third_1

a2=np.random.randint(0,6,1)
a3=np.random.randint(0,6,1)
a4=np.random.randint(0,6,1)
a5=np.random.randint(0,6,1)
a6=np.random.randint(0,6,1)
a7=sum([a1,a2,a3,a4,a5,a6])
print(a1,a2,a3,a4,a5,a6,a7)

[5] [5] [4] [0] [1] [5] [20]


In [22]:
#third_2
X=np.random.randint(10,60,1)
X

array([57])

In [30]:
#fourth_1
def Random_integer()
print(np.random.randint(0,10,1))
N=np.zero(2,3)
for a in range(6)
N[a]=Random_integer(a)
print(N）

SyntaxError: invalid syntax (3353774347.py, line 2)

In [34]:
#fifth_1
n=5
m=8
M=np.random.randint(0,2,(n,m))
M[[0,-1],[0,-1]]=1
print(M)

[[1 1 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 1]
 [1 0 1 0 0 1 0 0]
 [0 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 1]]
